#ifndef APPIMAGE_UPDATER_BRIDGE_STATUS_CODES_HPP_INCLUDED
#define APPIMAGE_UPDATER_BRIDGE_STATUS_CODES_HPP_INCLUDED

namespace AppImageUpdaterBridge {
    enum : short {
        INITIALIZING = 0,
        IDLE = 1,
        OPENING_APPIMAGE,
        CALCULATING_APPIMAGE_SHA1_HASH,
        READING_APPIMAGE_MAGIC_BYTES,
        FINDING_APPIMAGE_ARCHITECTURE,
        MAPPING_APPIMAGE_TO_MEMORY,
        SEARCHING_FOR_UPDATE_INFORMATION_SECTION_HEADER,
        UNMAPPING_APPIMAGE_FROM_MEMORY,
        FINALIZING_APPIMAGE_EMBEDED_UPDATE_INFORMATION,
        PARSING_APPIMAGE_EMBEDED_UPDATE_INFORMATION = 50,
        REQUESTING_GITHUB_API,
        PARSING_GITHUB_API_RESPONSE,
        REQUESTING_ZSYNC_CONTROL_FILE,
        REQUESTING_BINTRAY,
        PARSING_BINTRAY_REDIRECTED_URL_FOR_LATEST_PACKAGE_URL,
        PARSING_ZSYNC_CONTROL_FILE,
        SEARCHING_TARGET_FILE_CHECKSUM_BLOCK_OFFSET_IN_ZSYNC_CONTROL_FILE,
        STORING_ZSYNC_CONTROL_FILE_DATA_TO_MEMORY,
        FINALIZING_PARSING_ZSYNC_CONTROL_FILE,
        WRITTING_DOWNLOADED_BLOCK_RANGES = 100,
        EMITTING_REQUIRED_BLOCK_RANGES,
        CHECKING_CHECKSUMS_FOR_DOWNLOADED_BLOCK_RANGES,
        WRITTING_DOWNLOADED_BLOCK_RANGES_TO_TARGET_FILE,
        CALCULATING_TARGET_FILE_SHA1_HASH,
	CONSTRUCTING_TARGET_FILE
     };
}
#endif // APPIMAGE_UPDATER_BRIDGE_STATUS_CODES_HPP_INCLUDED
